---
title: "Logos"
author: "Zeki Akyol"
institute: "Istanbul Technical University"
format: html
---

# Packages

```{r}
library(here)
library(png)
library(grid)
library(hexSticker)
library(showtext)
library(ggforce)
library(tidyverse)
```

# Econometrics

```{r}
# Create Dataset:
set.seed(2)
simulation_size <- 10000000
df_econometrics <- tibble(group = rep(c("a", "b"), each = simulation_size),
                          samples = c(rnorm(n = simulation_size, mean = 7, sd = 4),
                                      rnorm(n = simulation_size, mean = 0, sd = 8)))

# Create Subplot:
p_econometrics <- ggplot(data = df_econometrics, aes(x = samples, fill = factor(group))) +
  geom_density(alpha = 0.8, color = "black", show.legend = FALSE) +
  scale_fill_manual(values = c("magenta", "#75F8FF")) +
  theme_void()

# Create Sticker:
sticker(p_econometrics,           # Subplot
        s_x = 1,                  # Subplot x coordinate
        s_y = 1.23,               # Subplot y coordinate
        s_width = 1.5,            # Subplot width
        s_height = 1.1,           # Subplot height
        package = "Econometrics", # Text
        p_size = 70,              # Text size
        p_color = "#FFFFFF",      # Text color
        p_y = 0.59,               # Text y coordinate
        h_fill = "#000000",       # Hex background color
        h_size = 6,               # Hex border size
        h_color = "#FCCE09",      # Hex border color
        # url = "github.com/zekiakyol/Econometrics", # Url text [this 4 lines will be uncommented when notes are public]
        # u_color = "white",                         # Url text color
        # u_size = 15,                               # Url text color
        # u_y = 0.07,                                # Url y coordinate
        dpi = 300,
        filename = here("logos_png", "econometrics_logo.png")) # ggsave() will override the default png on this line

# Save the sticker as a rectangle (keeps original dimension ratio of hexagon):
ggsave(filename = here("logos_png", "econometrics_logo.png"),
       width = 2072, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)

# Save the sticker as a square:
ggsave(filename = here("logos_png", "econometrics_logo_square.png"),
       width = 2400, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)
```

# Mathematical Economics

```{r}
# Create Subplot:
p_mathecon <- ggplot() +
  stat_function(fun = cos,
                color = "red",
                lwd = 2.5,
                geom = "point") +
  xlim(c(-1, 5)) +
  theme_void()

# Create Sticker:
sticker(p_mathecon,                         # Subplot
        s_x = 1,                            # Subplot x coordinate
        s_y = 1.15,                         # Subplot y coordinate
        s_width = 1.1,                      # Subplot width
        s_height = 1,                       # Subplot height
        package = "Mathematical Economics", # Text
        p_size = 43,                        # Text size
        p_color = "#FFFFFF",                # Text color
        p_y = 0.56,                         # Text y coordinate
        h_fill = "#000000",                 # Hex background color
        h_size = 6,                         # Hex border size
        h_color = "#FCCE09",                # Hex border color
        dpi = 300,
        filename = here("logos_png", "mathematical_economics_logo.png")) # ggsave() will override the default png on this line

# Save the sticker as a rectangle (keeps original dimension ratio of hexagon):
ggsave(filename = here("logos_png", "mathematical_economics_logo.png"),
       width = 2072, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)

# Save the sticker as a square:
ggsave(filename = here("logos_png", "mathematical_economics_logo_square.png"),
       width = 2400, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)
```

# Statistical Methods in Economics

```{r}
# Create Subplot:
p_statecon <- ggplot() +
  annotate("rect", xmin = -2, xmax = 5, ymin = 0, ymax = 10, color = "white", fill = "white", size = 2) +
  annotate("rect", xmin = 5, xmax = 12, ymin = 0, ymax = 10, color = "white", fill = "black", size = 2) +
  annotate("text", x = 1.5, y = 5, label = "H", size = 200, color = "black") +
  annotate("text", x = 8.5, y = 5, label = "T", size = 200, color = "white") +
  theme_void()

# Create Sticker:
sticker(p_statecon,                                   # Subplot
        s_x = 1,                                      # Subplot x coordinate
        s_y = 1.15,                                   # Subplot y coordinate
        s_width = 1,                                  # Subplot width
        s_height = 0.9,                               # Subplot height
        package = "Statistical Methods in Economics", # Text
        p_size = 33,                                  # Text size
        p_color = "#FFFFFF",                          # Text color
        p_y = 0.56,                                   # Text y coordinate
        h_fill = "#000000",                           # Hex background color
        h_size = 6,                                   # Hex border size
        h_color = "#FCCE09",                          # Hex border color
        dpi = 300,
        filename = here("logos_png", "statistical_methods_in_economics_logo.png")) # ggsave() will override the default png on this line

# Save the sticker as a rectangle (keeps original dimension ratio of hexagon):
ggsave(filename = here("logos_png", "statistical_methods_in_economics_logo.png"),
       width = 2072, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)

# Save the sticker as a square:
ggsave(filename = here("logos_png", "statistical_methods_in_economics_logo_square.png"),
       width = 2400, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)
```

# Research Methods in Economics

```{r}
# Create Dataset:
df_researchecon <- tibble(year = rep(-2:2, times = 2),
                          person = rep(c("A", "B"), each = 5),
                          wage = c(3, 4, 5, 8, 11, 1, 2, 3, 4, 5))

# Create Subplot:
p_researchecon <- ggplot(df_researchecon, aes(x = year, y = wage, color = factor(person))) +
  geom_vline(xintercept = 0, size = 2, color = "white", linetype = "longdash") +
  geom_line(size = 7, show.legend = FALSE) +
  scale_colour_manual(values = c(A = "#EC2E5D", B = "#54B972")) +
  ylim(0, 15) +
  theme_void()

# Create Sticker:
sticker(p_researchecon,                               # Subplot
        s_x = 1,                                      # Subplot x coordinate
        s_y = 1.2,                                    # Subplot y coordinate
        s_width = 1.2,                                # Subplot width
        s_height = 1,                                 # Subplot height
        package = "Research Methods in Economics",    # Text
        p_size = 34,                                  # Text size
        p_color = "#FFFFFF",                          # Text color
        p_y = 0.56,                                   # Text y coordinate
        h_fill = "#000000",                           # Hex background color
        h_size = 6,                                   # Hex border size
        h_color = "#FCCE09",                          # Hex border color
        dpi = 300,
        filename = here("logos_png", "research_methods_in_economics_logo.png")) # ggsave() will override the default png on this line

# Save the sticker as a rectangle (keeps original dimension ratio of hexagon):
ggsave(filename = here("logos_png", "research_methods_in_economics_logo.png"),
       width = 2072, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)

# Save the sticker as a square:
ggsave(filename = here("logos_png", "research_methods_in_economics_logo_square.png"),
       width = 2400, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)
```

# Advanced Econometrics

```{r}
# Create Subplot:
p_advanced_econometrics <- ggplot() +
  annotate("text",
           x = 5, y = 6.3,
           color = "#00FF41", size = 180,
           label = "0 1") + 
  annotate("text",
           x = 0.1, y = 7,
           color = "#00FF41", size = 200,
           label = "[",
           alpha = 0.2) + 
  annotate("text",
           x = 9.9, y = 7,
           color = "#00FF41", size = 200,
           label = "]",
           alpha = 0.2) + 
  xlim(0, 10) +
  ylim(0, 10) +
  theme_void()

# Create Sticker:
sticker(p_advanced_econometrics,                      # Subplot
        s_x = 1,                                      # Subplot x coordinate
        s_y = 1,                                      # Subplot y coordinate
        s_width = 1.2,                                # Subplot width
        s_height = 1,                                 # Subplot height
        package = "Advanced Econometrics",            # Text
        p_size = 42,                                  # Text size
        p_color = "#FFFFFF",                          # Text color
        p_y = 0.60,                                   # Text y coordinate
        h_fill = "#000000",                           # Hex background color
        h_size = 6,                                   # Hex border size
        h_color = "#FCCE09",                          # Hex border color
        dpi = 300,
        filename = here("logos_png", "advanced_econometrics_logo.png")) # ggsave() will override the default png on this line

# Save the sticker as a rectangle (keeps original dimension ratio of hexagon):
ggsave(filename = here("logos_png", "advanced_econometrics_logo.png"),
       width = 2072, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)

# Save the sticker as a square:
ggsave(filename = here("logos_png", "advanced_econometrics_logo_square.png"),
       width = 2400, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)
```

# Machine Learning Readings

```{r}
# Create Subplot:
coordinate_color <- "white"
shape_color <- "#009641"

positions_lasso <- data.frame(
  id = c( "east", "north", "west", "south"),
  x = c(1, 2, 3, 2),
  y = c(5, 6, 5, 4)
)

positions_elasticnet <- data.frame(
  id = c( "east", "north", "west", "south"),
  x = c(7, 8, 9, 8),
  y = c(5, 6, 5, 4)
)

p_mlreadings <- ggplot() +
  geom_circle(aes(x0 = 5, y0 = 5, r = 1), color = shape_color, fill = shape_color) +
  geom_polygon(aes(x = x, y = y), color = shape_color, fill = shape_color, data = positions_lasso) + 
  geom_polygon(aes(x = x, y = y), color = shape_color, fill = shape_color, data = positions_elasticnet) + 
  geom_curve(aes(x = 7.05, y = 5, xend = 8, yend = 5.95), color = shape_color, size = 2.1, curvature = -0.15) +
  geom_curve(aes(x = 7.05, y = 5, xend = 8, yend = 4.05), color = shape_color, size = 2.1, curvature = 0.15) +
  geom_curve(aes(x = 8.95, y = 5, xend = 8, yend = 5.95), color = shape_color, size = 2.1, curvature = 0.15) +
  geom_curve(aes(x = 8.95, y = 5, xend = 8, yend = 4.05), color = shape_color, size = 2.1, curvature = -0.15) +
  geom_segment(aes(x = 2, y = 3, xend = 2, yend = 7), color = coordinate_color, size = 1) + 
  geom_segment(aes(x = 5, y = 3, xend = 5, yend = 7), color = coordinate_color, size = 1) +
  geom_segment(aes(x = 8, y = 3, xend = 8, yend = 7), color = coordinate_color, size = 1) + 
  geom_segment(aes(x = 0, y = 5, xend = 10, yend = 5), color = coordinate_color, size = 1) +
  xlim(c(0, 10)) +
  ylim(c(0, 10)) + 
  coord_fixed() +
  theme_void()

# Create Sticker:
sticker(p_mlreadings,                           # Subplot
        s_x = 1,                                # Subplot x coordinate
        s_y = 1.1,                              # Subplot y coordinate
        s_width = 1.6,                          # Subplot width
        s_height = 1.6,                         # Subplot height
        package = "Machine Learning Readings",  # Text
        p_size = 41,                            # Text size
        p_color = "#FFFFFF",                    # Text color
        p_y = 0.60,                             # Text y coordinate
        h_fill = "#000000",                     # Hex background color
        h_size = 6,                             # Hex border size
        h_color = "#FCCE09",                    # Hex border color
        dpi = 300,
        filename = here("logos_png", "mlreadings_logo.png")) # ggsave() will override the default png on this line

# Save the sticker as a rectangle (keeps original dimension ratio of hexagon):
ggsave(filename = here("logos_png", "mlreadings_logo.png"),
       width = 2072, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)

# Save the sticker as a square:
ggsave(filename = here("logos_png", "mlreadings_logo_square.png"),
       width = 2400, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)
```


# Proof-Based Math Readings

```{r}
# Create Subplot:
data_proofbasedmath_readings <- tibble(x = c(0:10,
                                             0:10,
                                             0:3),
                                       y = c(rep(9, times = 11),
                                             rep(5, times = 11),
                                             rep(1, times = 4)))

p_proofbasedmath_readings <- ggplot(data_proofbasedmath_readings, aes(x = x, y = y)) +
  geom_point(color = "white", shape = "square", size = 3) +
  geom_point(aes(x = 5, y = 1), color = "red", shape = "square", size = 12) +
  xlim(c(0, 10)) +
  ylim(c(0, 10)) +
  coord_fixed() +
  theme_void()

# Create Sticker:
sticker(p_proofbasedmath_readings,              # Subplot
        s_x = 1,                                # Subplot x coordinate
        s_y = 1.1,                              # Subplot y coordinate
        s_width = 1,                            # Subplot width
        s_height = 1,                           # Subplot height
        package = "Proof-Based Math Readings",  # Text
        p_size = 41,                            # Text size
        p_color = "#FFFFFF",                    # Text color
        p_y = 0.60,                             # Text y coordinate
        h_fill = "#000000",                     # Hex background color
        h_size = 6,                             # Hex border size
        h_color = "#FCCE09",                    # Hex border color
        dpi = 300,
        filename = here("logos_png", "proofbasedmath_readings_logo.png")) # ggsave() will override the default png on this line

# Save the sticker as a rectangle (keeps original dimension ratio of hexagon):
ggsave(filename = here("logos_png", "proofbasedmath_readings_logo.png"),
       width = 2072, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)

# Save the sticker as a square:
ggsave(filename = here("logos_png", "proofbasedmath_readings_logo_square.png"),
       width = 2400, height = 2400, units = "px",
       bg = "transparent",
       type = "cairo", # "cairo" requires installation of https://www.xquartz.org on our macOS machine
       dpi = 300)
```

```{r}
1 + 1 # trivial code to "Run All Chunks Above"
```
